version: "3.9"
services:
  admin:
    image: docker.io/tjohander/domain-home-in-image:14.1.1.0
    hostname: wlsadmin
    container_name: wsladmin
    ports:
      - "7001:7001"
      - "9002:9002"
    volumes:
      - ./weblogic/admin:/u01/oracle/properties
      - ./weblogic/admin/apps:/app
  ms1:
    image: docker.io/tjohander/domain-home-in-image:14.1.1.0
    ports:
      - "8001:8001"
    volumes:
      - ./weblogic/managed-server:/u01/oracle/properties
    environment:
      MANAGED_SERV_NAME: managed-server1
    command:
      - startManagedServer.sh
  ms2:
    image: docker.io/tjohander/domain-home-in-image:14.1.1.0
    ports:
      - "8002:8001"
    volumes:
      - ./weblogic/managed-server:/u01/oracle/properties
    environment:
      MANAGED_SERV_NAME: managed-server2
    command:
      - startManagedServer.sh
  prometheus:
    image: prom/prometheus
    volumes:
      - ./weblogic/prometheus/config:/etc/prometheus
    ports:
      - "9090:9090"
  otel:
    image: quay.io/signalfx/splunk-otel-collector:latest
    ports:
      - "5000:5000"
      - '13133:13133'
      - '14250:14250'
      - '14268:14268'
      - '4317:4317'
      - '6060:6060'
      - '8888:8888'
      - '9080:9080'
      - '9411:9411'
      - '9943:9943'
    volumes:
      - ./weblogic/otel:/etc/otel/collector
    env_file: ./weblogic/otel/.env