query_sync:
  url: http://coordinator:8999/
  interval: 5
metricsNameSnakeCase: true
domainQualifier: true
queries:
  - key: name
    keyName: server
    applicationRuntimes:
      key: name
      keyName: app
      componentRuntimes:
        type: WebAppComponentRuntime
        prefix: webapp_config_
        key: name
        values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount, openSessionsCurrentCount, sessionsOpenedTotalCount, sessionCookieMaxAgeSecs, sessionInvalidationIntervalSecs, sessionTimeoutSecs, singleThreadedServletPoolSize, sessionIDLength, servletReloadCheckSecs, jSPPageCheckSecs]
        servlets:
          prefix: weblogic_servlet_
          key: servletName
          values: [invocationTotalCount, reloadTotal, executionTimeAverage, poolMaxCapacity, executionTimeTotal, reloadTotalCount, executionTimeHigh, executionTimeLow]
  - key: name
    keyName: server
    JVMRuntime:
      prefix: jvm_
      key: name
      values: [ heapFreeCurrent, heapFreePercent, heapSizeCurrent, heapSizeMax, processCpuLoad, uptime ]