global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: oracle_web_logic
    static_configs:
        - targets: [ 'admin:7001', 'ms1:8001', 'ms2:8001' ]
    metrics_path: '/wls-exporter/metrics'
    basic_auth:
      username: myuser
      password: mypassword1
  - job_name: spring-pet-clinic
    static_configs:
      - targets: [ 'admin:7001', 'ms1:8001', 'ms2:8001' ]
    metrics_path: '/petclinic/actuator/prometheus'